### ISSUE TITLE
WAYS TO IMPROVE UNCVRD SITE

### ISSUE THREAD

**Issue by Souadish** [uncvrd/uncvrd-website#4]
**VOLUME SLIDE**
**THE SONG I WANT TO LISTEN TO ISN'T THE ONE THAT PLAYS**
**CAN'T FULLY SCROLL DOWN THE PAGE**
i think that's it
<3

**Comment by uncvrd** [comment]
Scrolling issue is fixed now! Working on volume slider for desktop now
