### ISSUE TITLE
Link issues 

### ISSUE THREAD

**Issue by MccallumM** [uncvrd/uncvrd-website#5]
occasionally when switching between artist, curator links back to the homepage the videos will not play. there is 2 variations. one is with the video in the corner the other is without the video. 
![image](https://cloud.githubusercontent.com/assets/25109920/21945408/058b9774-d9d3-11e6-94b0-f916254f5b67.png) 
![image](https://cloud.githubusercontent.com/assets/25109920/21945413/118e99d6-d9d3-11e6-9d37-9ba7d6420f6b.png)

**Comment by uncvrd** [comment]
Top screenshot is because there is no youtube url that was added to the post, so no issue here just an oversight on posting the article on my end. Second one is an issue I'm fixing right now. I'll keep you posted, thanks Morgan!

**Comment by uncvrd** [comment]
Update has been pushed to the site, should be fixed now :)
